### ISSUE TITLE
Unable to parse code with "Null coalescing operator"

### ISSUE THREAD

**Issue by kudlav** [voda/gettext-extractor#20]
Unable to parse following line of code:
```PHP
$foo = $bar ?? 'none';
```

New feature in PHP 7: [http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op)

Result:
```bash
PHP Notice:  Undefined offset: 282 in vendor/nikic/php-parser/lib/PHPParser/Lexer.php on line 121
PHP Notice:  Undefined index:  in vendor/nikic/php-parser/lib/PHPParser/Parser.php on line 983
PHP Notice:  Undefined index:  in vendor/nikic/php-parser/lib/PHPParser/Parser.php on line 1099
PHP Fatal error:  Uncaught PHPParser_Error: Syntax error, unexpected  on line 34 in vendor/nikic/php-parser/lib/PHPParser/Parser.php:1098
Stack trace:
#0 vendor/voda/gettext-extractor/GettextExtractor/Filters/PHPFilter.php(41): PHPParser_Parser->parse('<?php\n\nnamespac...')
#1 vendor/voda/gettext-extractor/GettextExtractor/Extractor.php(193): GettextExtractor_Filters_PHPFilter->extract('./app/FrontModu...')
#2 vendor/voda/gettext-extractor/GettextExtractor/Extractor.php(139): GettextExtractor_Extractor->_extract(Array)
#3 vendor/voda/gettext-extractor/gettext-extractor.php(113): GettextExtractor_Extractor->scan(Array)
#4 {main}
  thrown in vendor/nikic/php-parser/lib/PHPParser/Parser.php on line 1098
```

**Comment by voda** [comment]
Hi, thank you for your report. This is now fixed in the newly released version v4.0.0.
